language: node_js
node_js:
  - 8
cache:
  directories:
    - node_modules
before_install:
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc
before_script :
- curl -o- -L https://yarnpkg.com/install.sh | bash -s
- export PATH=$HOME/.yarn/bin:$PATH
- yarn install
script:
  - yarn run test
  - yarn run build
