language: node_js
node_js:
  - 11.6.0
cache:
  directories:
    - node_modules
before_install:
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc
script:
  - yarn run test
  - yarn run build
