language: node_js
node_js:
  - 'stable'
cache:
  directories:
    - node_modules
before_install:
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc
script:
  - yarn run test
  - yarn run build
deploy:
  provider: surge
  skip_cleanup: true
  domain: omniscient-father.surge.sh
  project: ./build/
  on:
    branch: master
